---
- name: SETUP NETWORK JOBS IN TOWER
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: REMOVE DEMO JOB TEMPLATE
      tower_job_template:
        name: "Demo Job Template"
        job_type: "run"
        project: "Demo Project"
        state: absent
        playbook: "null"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: CREATE BACKUP JOB TEMPLATE
      tower_job_template:
        name: "BACKUP NETWORK CONFIG"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_backup.yml"
        credential: "Workshop Credential"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: Recursively find /tmp files older than 2 days
      find:
        paths: /tmp/backup
      register: backups

    # - name: show files
    #   debug:
    #     var: backups.files
    #
    # - name: show each file
    #   debug:
    #     msg: "{{item.path.split('.')[-1]}}"
    #   loop: "{{backups.files}}"

    - name: test template
      template:
        src: templates/backup.j2
        dest: ./rendered.txt

    - name: CREATE RESTORE JOB TEMPLATE
      tower_job_template:
        name: "RESTORE NETWORK CONFIG"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_restore.yml"
        credential: "Workshop Credential"
        survey_enabled: true
        survey_spec: "{{ lookup('file', '{{playbook_dir}}/templates/backup.j2') }}"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    # - name: sean test
    #   uri:
    #     url: https://localhost/api/v2/job_templates/9/survey_spec/
    #     method: POST
    #     user: admin
    #     password: ansible
    #     validate_certs: False
    #     body: "{{ lookup('file', '{{playbook_dir}}/templates/backup.j2') }}"
    #     body_format: json
    #     force_basic_auth: yes
